<?php
// =====================================================
// api/font-catalog.php — プロンプト埋め込み用フォントカタログ
// js/font-list.js と同じ書体を family / category / subset のみで保持。
// （weights はプロンプトに不要なので含めない＝トークン節約）
//
// ※ 書体を追加・変更する場合は js/font-list.js と本ファイルの両方を更新すること。
// =====================================================

function get_font_catalog(): array {
    return [
        // 和文（subset: "jp"）
        ['family' => 'Noto Sans JP',               'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Noto Serif JP',              'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'M PLUS Rounded 1c',          'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'M PLUS 1p',                  'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Zen Kaku Gothic New',        'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Zen Maru Gothic',            'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Sawarabi Mincho',            'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'Shippori Mincho',            'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'Sawarabi Gothic',            'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'LINE Seed JP',               'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'IBM Plex Sans JP',           'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'BIZ UDPGothic',              'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Zen Old Mincho',             'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'Kosugi Maru',                'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'M PLUS 1',                   'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Dela Gothic One',            'category' => 'display',     'subset' => 'jp'],
        ['family' => 'Zen Kaku Gothic Antique',    'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Kaisei Decol',               'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'Shippori Mincho B1',         'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'M PLUS 2',                   'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Hachi Maru Pop',             'category' => 'handwriting', 'subset' => 'jp'],
        ['family' => 'Potta One',                  'category' => 'display',     'subset' => 'jp'],
        ['family' => 'Murecho',                    'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Kiwi Maru',                  'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'BIZ UDGothic',               'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Yuji Mai',                   'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'DotGothic16',                'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Kosugi',                     'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Rampart One',                'category' => 'display',     'subset' => 'jp'],
        ['family' => 'Klee One',                   'category' => 'handwriting', 'subset' => 'jp'],
        ['family' => 'Hina Mincho',                'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'BIZ UDPMincho',              'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'Mochiy Pop One',             'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'RocknRoll One',              'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Yusei Magic',                'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Cherry Bomb One',            'category' => 'display',     'subset' => 'jp'],
        ['family' => 'Zen Antique',                'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'Monomaniac One',             'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Kaisei Opti',                'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'Yuji Syuku',                 'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'Zen Kurenaido',              'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Zen Antique Soft',           'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'Reggae One',                 'category' => 'display',     'subset' => 'jp'],
        ['family' => 'Aoboshi One',                'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'Shippori Antique',           'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Train One',                  'category' => 'display',     'subset' => 'jp'],
        ['family' => 'Kaisei Tokumin',             'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'Mochiy Pop P One',           'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'M PLUS 1 Code',              'category' => 'monospace',   'subset' => 'jp'],
        ['family' => 'Yomogi',                     'category' => 'handwriting', 'subset' => 'jp'],
        ['family' => 'Stick',                      'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'New Tegomin',                'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'BIZ UDMincho',               'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'Kapakana',                   'category' => 'handwriting', 'subset' => 'jp'],
        ['family' => 'Shippori Antique B1',        'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Kaisei HarunoUmi',           'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'Yuji Boku',                  'category' => 'serif',       'subset' => 'jp'],
        ['family' => 'WDXL Lubrifont JP N',        'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Darumadrop One',             'category' => 'display',     'subset' => 'jp'],
        ['family' => 'Shizuru',                    'category' => 'display',     'subset' => 'jp'],
        ['family' => 'Tsukimi Rounded',            'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Chokokutai',                 'category' => 'display',     'subset' => 'jp'],
        ['family' => 'Palette Mosaic',             'category' => 'display',     'subset' => 'jp'],
        ['family' => 'Rock 3D',                    'category' => 'display',     'subset' => 'jp'],
        ['family' => 'M PLUS U',                   'category' => 'sans-serif',  'subset' => 'jp'],
        ['family' => 'Slackside One',              'category' => 'handwriting', 'subset' => 'jp'],
        ['family' => 'Yuji Hentaigana Akari',      'category' => 'handwriting', 'subset' => 'jp'],
        ['family' => 'Yuji Hentaigana Akebono',    'category' => 'handwriting', 'subset' => 'jp'],

        // 欧文（subset: "latin"）
        ['family' => 'Roboto',                     'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Open Sans',                  'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Google Sans',                'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Inter',                      'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Montserrat',                 'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Poppins',                    'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Lato',                       'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Material Icons',             'category' => 'monospace',   'subset' => 'latin'],
        ['family' => 'Arimo',                      'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Roboto Condensed',           'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Roboto Mono',                'category' => 'monospace',   'subset' => 'latin'],
        ['family' => 'Noto Sans',                  'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Oswald',                     'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Raleway',                    'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Nunito Sans',                'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Nunito',                     'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'DM Sans',                    'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Playfair Display',           'category' => 'serif',       'subset' => 'latin'],
        ['family' => 'Rubik',                      'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Roboto Slab',                'category' => 'serif',       'subset' => 'latin'],
        ['family' => 'Noto Sans KR',               'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Material Symbols Outlined',  'category' => 'monospace',   'subset' => 'latin'],
        ['family' => 'Archivo Black',              'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Ubuntu',                     'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Kanit',                      'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Merriweather',               'category' => 'serif',       'subset' => 'latin'],
        ['family' => 'Manrope',                    'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Outfit',                     'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Work Sans',                  'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Noto Sans TC',               'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Lora',                       'category' => 'serif',       'subset' => 'latin'],
        ['family' => 'Bebas Neue',                 'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'PT Sans',                    'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Mulish',                     'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Prompt',                     'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'IBM Plex Sans',              'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Source Sans 3',              'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Figtree',                    'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Saira',                      'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Black Ops One',              'category' => 'display',     'subset' => 'latin'],
        ['family' => 'Inconsolata',                'category' => 'monospace',   'subset' => 'latin'],
        ['family' => 'Barlow',                     'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Quicksand',                  'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Plus Jakarta Sans',          'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Bricolage Grotesque',        'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Fira Sans',                  'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Karla',                      'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Share Tech',                 'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Smooch Sans',                'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Material Icons Outlined',    'category' => 'monospace',   'subset' => 'latin'],
        ['family' => 'Jost',                       'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Titillium Web',              'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Archivo',                    'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Noto Serif',                 'category' => 'serif',       'subset' => 'latin'],
        ['family' => 'Source Code Pro',            'category' => 'monospace',   'subset' => 'latin'],
        ['family' => 'Heebo',                      'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Dancing Script',             'category' => 'handwriting', 'subset' => 'latin'],
        ['family' => 'PT Serif',                   'category' => 'serif',       'subset' => 'latin'],
        ['family' => 'Noto Color Emoji',           'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Fjalla One',                 'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Cormorant Garamond',         'category' => 'serif',       'subset' => 'latin'],
        ['family' => 'JetBrains Mono',             'category' => 'monospace',   'subset' => 'latin'],
        ['family' => 'Noto Sans SC',               'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Libre Baskerville',          'category' => 'serif',       'subset' => 'latin'],
        ['family' => 'Libre Franklin',             'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Lobster Two',                'category' => 'display',     'subset' => 'latin'],
        ['family' => 'Space Grotesk',              'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Barlow Condensed',           'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Changa One',                 'category' => 'display',     'subset' => 'latin'],
        ['family' => 'Anton',                      'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Public Sans',                'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Material Symbols Rounded',   'category' => 'monospace',   'subset' => 'latin'],
        ['family' => 'Josefin Sans',               'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Nanum Gothic',               'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Cairo',                      'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Instrument Serif',           'category' => 'serif',       'subset' => 'latin'],
        ['family' => 'EB Garamond',                'category' => 'serif',       'subset' => 'latin'],
        ['family' => 'Sora',                       'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Alfa Slab One',              'category' => 'display',     'subset' => 'latin'],
        ['family' => 'Material Icons Round',       'category' => 'monospace',   'subset' => 'latin'],
        ['family' => 'Assistant',                  'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Inter Tight',                'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Caveat',                     'category' => 'handwriting', 'subset' => 'latin'],
        ['family' => 'Cabin',                      'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Schibsted Grotesk',          'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Noto Sans Telugu',           'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Ramabhadra',                 'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Roboto Flex',                'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Dosis',                      'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Hind Siliguri',              'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Bitter',                     'category' => 'serif',       'subset' => 'latin'],
        ['family' => 'Red Hat Display',            'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Anek Telugu',                'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Noto Sans Khmer',            'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Overpass',                   'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Rajdhani',                   'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Mukta',                      'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Lexend',                     'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Oxygen',                     'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Exo 2',                      'category' => 'sans-serif',  'subset' => 'latin'],
        ['family' => 'Space Mono',                 'category' => 'monospace',   'subset' => 'latin'],
    ];
}
